apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: devops-app-prod

namespace: devops-app-prod

resources:
  - ../../base
  - ingress.yaml
  - hpa.yaml

patchesStrategicMerge:
  - deployment-patch.yaml

replicas:
  - name: devops-app
    count: 3

images:
  - name: devops-app
    newTag: v1.0.0

commonLabels:
  environment: prod

configMapGenerator:
  - name: app-config
    literals:
      - LOG_LEVEL=WARNING
      - DEBUG=false 