apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: devops-app-base

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: devops-app
  version: v1.0.0

commonAnnotations:
  app.kubernetes.io/name: devops-app
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: devops-platform

images:
  - name: devops-app
    newTag: latest 