apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  template:
    spec:
      containers:
      - name: devops-app
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: DEBUG
          value: "true"
        - name: FLASK_ENV
          value: "development"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m" 