apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: devops-app-dev

namespace: devops-app-dev

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

replicas:
  - name: devops-app
    count: 1

images:
  - name: devops-app
    newTag: dev-latest

commonLabels:
  environment: dev

configMapGenerator:
  - name: app-config
    literals:
      - LOG_LEVEL=DEBUG
      - DEBUG=true 