apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  template:
    spec:
      containers:
      - name: devops-app
        env:
        - name: LOG_LEVEL
          value: "INFO"
        - name: DEBUG
          value: "false"
        - name: FLASK_ENV
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m" 