apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: devops-app-staging

namespace: devops-app-staging

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml

replicas:
  - name: devops-app
    count: 2

images:
  - name: devops-app
    newTag: staging-latest

commonLabels:
  environment: staging

configMapGenerator:
  - name: app-config
    literals:
      - LOG_LEVEL=INFO
      - DEBUG=false 